// Angular Version/src/app/quote-box/quote-box.component.ts
import { Component, OnInit } from '@angular/core';
import { QuoteService } from '../quote.service';
import { Quote } from '../quote.class';

@Component({
  selector: 'app-qoute-box',
  templateUrl: './quote-box.component.html',
  styleUrls: ['./quote-box.component.scss']
})
export class QuoteBoxComponent implements OnInit {
  public quote = new Quote('', '');
  constructor(public quoteService: QuoteService) {
    this.getQuote();
  }

  public getQuote() {
    this.quoteService.getRandomQuote().subscribe((data: Quote) => {
      this.quote = new Quote(data.quote, data.author);
    });
  }

  ngOnInit() {
  }

}

<div class="container text-center">
  <div class="row justify-content-center">
    <div class="card text-success mt-5" style="width: 30rem">
      <blockquote class="blockquote">
        <p class="mb-0 p-3">
          <i class="fa fa-quote-left fa-lg"></i> {{quote.quote}}
        </p>
        <footer class="blockquote-footer text-success" [innerText]="quote.author"></footer>
      </blockquote>
      <div class="row justify-content-center">
        <a target="blank" class="btn btn-outline-success m-2" [href]="'https:/twitter.com/intent/tweet/?text=' + quote.quote">
          <i class="fab fa-twitter"></i>
        </a>

        <button class="btn btn-outline-success m-2" (click)="getQuote()">
          <i class="fas fa-plus"></i>
        </button>
      </div>
    </div>
  </div>
</div>

// React Version/src/quoteBox.jsx
import React, { Component } from "react";
import Twitter from "./twiter";
import "./quoteBox.css";

class QuoteBox extends Component {
  constructor(props) {
    super(props);
    this.state = {
      quote: "",
      author: ""
    };
  }

  handleQuoteChange = () => {
    fetch("https://talaikis.com/api/quotes/random/")
      .then(res => res.json())
      .then(data => this.setState({ quote: data.quote, author: data.author }));
  };

  componentDidMount() {
    fetch("https://talaikis.com/api/quotes/random/")
      .then(res => res.json())
      .then(data => this.setState({ quote: data.quote, author: data.author }));
  }

  render() {
    return (
      <div className="container">
        <div className="row justify-text-center">
          <div className="card text-success mt-5 mx-auto">
            <blockquote className="blockquote">
              <p className="mb-0 p-3">
                <i className="fa fa-quote-left fa-lg" />
                {this.state.quote}
              </p>
              <footer className="blockquote-footer text-success ml-3">
                {this.state.author}
              </footer>
            </blockquote>
            <div className="text-center mb-2">
              <Twitter link={this.state.quote} />
              <button
                type="button"
                className="btn btn-success ml-2"
                onClick={this.handleQuoteChange}
              >
                <i className="fas fa-plus" />
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default QuoteBox;
